---
title: "State TaxData Enhancement Project -- Task 2"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook: 
    df_print: paged
    toc: yes
    toc_depth: 5
    number_sections: true
editor_options: 
  chunk_output_type: console
---

<!--
  Enclose comments for RMD files in these kinds of opening and closing brackets
-->



# Start of the program

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```


```{r system_specific_info, include=TRUE}
# change information here as needed
destdir <- "C:/Dropbox/AA_Projects_Work/Proj_taxData/Data/acs/"

#dbdir <- paste0(destdir, "rsqlite/") # location for sqlite database to be created
#dbf <- paste0(dbdir, "acs.sqlite") # database name; database will be created (if not already created) and used below

```


```{r includes, include=FALSE}
source(here::here("task2", "libraries_djb.r"))
source(here::here("task2", "functions_djb.r"))
source(here::here("task2", "functions_optimization_djb.r"))
source(here::here("task2", "functions_ipoptr.R"))
```


# Constructing a subset of ACS data

```{r}

persons_all <- readRDS(paste0(destdir, "persons.rds"))
glimpse(persons_all)
ns(persons_all)

states_select <- c("CA", "NY", "TX", "IL", "FL") # 5 large very different states
n_sample      <- 50e3
set.seed(1234)

acs_subset <- persons_all %>% 
  filter(stabbr %in% states_select, !is.na(pincp), agep >= 18) %>% 
  sample_n(n_sample) %>% 
  select(-st) %>% 
  mutate(otherincp = pincp - (intp + pap + retp + ssip + ssp + wagp),
         weightp   = pwgtp) # equal to original pwgt, for constructing constraints

glimpse(acs_subset)


saveRDS(acs_subset, paste0(PROJHOME, "/data/acs_subset.rds"))

glimpse(acs_subset)
ht(acs_subset)
summary(acs_subset)

# count(samp, stabbr) %>% mutate(share = 100 * n / sum(n))
# count(persons_all, stabbr) %>% filter(stabbr %in% states_select) %>% mutate(share = 100 * n / sum(n))
# 
# count(samp, sex) %>% mutate(share = 100 * n / sum(n))
# persons_all %>% filter(stabbr %in% states_select) %>% count(sex) %>% mutate(share = 100 * n / sum(n))
# 
# quantile(samp$agep)
# quantile(persons_all %>% filter(stabbr %in% states_select, agep>=18) %>% pull(agep))
# 
# quantile(samp$pincp)
# quantile(persons_all %>% filter(stabbr %in% states_select, agep>=18) %>% pull(pincp))
# quantile(persons_all %>% filter(agep>=18) %>% pull(pincp))
# 


## Key variable 

# serialno: family ID
# sporder : family member ID
# stabbr  : state abbreviation
# pwgtp   : person weight, an integer NOTE: do not need to be divided by 100 as in the case of PUF
# sex
# agep    : age
# mar
# intp    : interest income 
# pap     : public assistance income
# pincp   : total person income
# retp    : retirement income
# ssip    : Supplemental Security Income
# ssp     : Social Security income
# wagp    : Wages

#------------------------------------------


### Original instruction
# # keep a few variables:
# # RECID unique id
# # E00100 AGI
# # E00200 wages
# # E00300 interest received -- not kept
# # E01700 pension income in AGI
# # E02000 schedule E net income 
# # S006 record weight as an integer - must be divided by 100
# vars <- c("RECID", "E00100", "E00200", "E01700", "E02000", "S006")
# set.seed(1234)
# pufsub <- pufraw %>% 
#   sample_n(5000) %>%
#   select(vars) %>%
#   mutate(weight=S006 / 100, otheragi=E00100 - E00200 - E01700 - E02000) %>%
#   select(-S006) %>%
#   select(RECID, weight, everything())
# 
# # glimpse(pufsub)
# # ht(pufsub)

```


# Setting target state and preparing recipe for constraint coefficients

```{r}
# Loading data
acs_subset <- readRDS(paste0(PROJHOME, "/data/acs_subset.rds"))
ht(acs_subset)
str(acs_subset)

# Set target state
target_state <- "All"   # "NY", "CA", "NY", "TX", "IL", "FL"

# Choose objective function
obj_fn <- c("xtop", "absapprox")[2]



# recipe for individual weights
acs_subset %<>% 
  mutate(pid = paste0(serialno, sporder))

record_recipe <- tibble(
  vname    = "weightp",
  valgroup = paste0("pid==", acs_subset$pid),
  fn       = "npos" 
)

# record_recipe %>% nrow




# create a recipe that says which ccoef's we want.

# As before, we want a df with 3 columns:
#  vname:     a character variable name
#  valgroup:  a character variable with a logical expression defining the data subgroup
#  fn:        a character variable giving a function name (or calculation label)
#             right now, the function get_ccoefs has definitions for sumval, npos, and nnegs
#             so that's what we'll use, but we could expand it of course


# Create a sub-recipe for file totals - must make sure valgroup is character 
totals_recipe <- read_csv("
  vname, valgroup, fn
  weightp, TRUE, npos
  pincp, TRUE, sumval
  pincp, TRUE, npos
  wagp,  TRUE, sumval
  intp,  TRUE, sumval
  intp,  TRUE, npos
  retp,  TRUE, sumval
  retp,  TRUE, npos
  ssp,   TRUE, sumval
  ssp,   TRUE, npos", col_types = cols(.default=col_character()))
totals_recipe


# Create a sub-recipe for state totals - must make sure valgroup is character

state_names     <- as.character(acs_subset$stabbr) %>% unique %>% sort

stateTot_recipe <- read_csv("
  vname, fn
  weightp, npos
  pincp, sumval
  pincp, npos
  wagp,  sumval
  intp,  sumval
  intp,  npos
  retp,  sumval
  retp,  npos
  ssp,   sumval
  ssp,   npos", col_types = cols(.default=col_character())) %>% 
  mutate(c_num = row_number())
stateTot_recipe

stateTot_recipe <- expand_grid(valgroup=paste0("stabbr=='", state_names,"'") , c_num = stateTot_recipe$c_num) %>% 
  left_join(stateTot_recipe, by = "c_num") %>% 
  select(vname, valgroup, fn)
stateTot_recipe


# Create a sub-recipe for pincp ranges
# Here we'll define pincp ranges seperately, for convenience
# There may be more efficient (less labor-intensive) ways to do this...

# 5 pincp ranges

# acs_subset$pincp %>% quantile(c(0, 0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99, 1)) # percentiles of the subset 
# persons_all$pincp[persons_all$stabbr %in% states_select & persons_all$agep >= 18 ] %>% quantile(c(0, 0.01, 0.1, 0.25, 0.5, 0.75, 0.9, 0.99, 1), na.rm = TRUE) # percentiles of the whole dataset
pincp_ranges <- read_csv("
pincprange
pincp<=0
pincp>0&pincp<=25e3
pincp>25e3&pincp<=50e3
pincp>50e3&pincp<=100e3
pincp>100e3")
pincp_ranges

vnames <- c("weightp",  "pincp",  "wagp", "intp", "retp", "ssp") #[c(1,2,3, 4)]
fns    <- c("sumval", "npos", "nneg")         #[c(1,2,3)]

# We are setting things up to define 5 x 4 x 3 = 60 constraints, here goes:
range_recipe <- expand_grid(vname = vnames, 
                            valgroup_range = pincp_ranges$pincprange, 
                            valgroup_state = paste0("stabbr=='", state_names,"'"),
                            fn = fns) 

# Excluding some constraints
range_recipe %<>%
    filter(!(vname == "weightp" & fn %in% c("sumval", "nneg"))) %>% # some of coeffs of npos is the total weight
    filter(!(vname == "ssp"     & fn %in% c("nneg")))
#   filter(!(vname == "pincp" & valgroup %in% c("pincp<=0"))) %>% 
#   filter(!(vname == "wagp" & valgroup %in% c("pincp<=0"))) %>% 
#   filter(!(vname == "retp" & valgroup %in% c("pincp<=0"))) %>% 
#   filter(!(vname == "intp" & valgroup %in% c("pincp<=0"))) %>% 
#   filter(!(vname == "intp" & fn %in% c("nneg"))) %>% # including sumval leads to failure 
#   filter(!(vname == "retp" & fn %in% c("npos", "nneg")))     # including sumval leads to failure 

range_recipe %<>% # combine range and state conditions
  mutate(valgroup = paste(valgroup_range, valgroup_state, sep = "&")) %>% 
  select(vname, valgroup, fn)

range_recipe


# now combine the two sub recipes
recipe <- bind_rows(totals_recipe, stateTot_recipe, range_recipe, record_recipe) %>% 
#recipe <- totals_recipe %>% 
  mutate(constraint_sort = row_number(),
         constraint_name = paste(vname, str_remove_all(valgroup, " "), fn, sep="_")) %>%
  select(constraint_sort, everything())
  
recipe



# Checking the number of constraints and nuber of non-zero coeffs

# To solve the optimization problem for 5 states, we need to create
# a data frame with 5 original df stacked together, each for an indiviudal state. 

acs_subset_stacked <- ldply(state_names, function(x) acs_subset %>% mutate(stabbr_original = stabbr, stabbr = x))
acs_subset_stacked %>% ht


ccoef_sparse_test <- recipe %>% 
  rowwise() %>% 
  do(get_ccoefs(., acs_subset_stacked)) %>% 
  ungroup
count(ccoef_sparse_test, constraint_sort, constraint_name)

ccoef_lowN_test <- # constraints with low # of non-zero coefficients 
  count(ccoef_sparse_test, constraint_sort, constraint_name) %>% 
  filter(n <=  nrow(acs_subset) / 1000)
ccoef_lowN_test

# Note that all state specific constraints on intp are removed due to low # of non-zero coefs. 

ccoef_sparse_test %<>% 
  filter((!constraint_name %in% ccoef_lowN_test$constraint_name) | constraint_sort >= 436) %>% 
# ONLY AFTER all filtering is done do we assign constraint numbers, as some
  # may drop out if they have no nonzero coefficients %>%
  mutate(constraint_num = group_indices(., constraint_sort)) %>%
  arrange(constraint_num, row_num) %>% 
  select(constraint_num, everything())
count(ccoef_sparse_test, constraint_num, constraint_sort, constraint_name)

# 285 of 375 constraints are kept (76%), most constraints for pincp <= 0 are dropped 

```


```{r}
run_ipopt_allstates <- function(recipe,
                                obj_fn,
                                data = acs_subset){
# Function inputs
#  - target_state
#  - acs_subset
#  - recipe
#  - obj_fn

data <- acs_subset
obj_fn <- "xtop"

# # names(persons_all)
# data_use[data_use$ssp >= 0, ] %>% nrow

##  Preparing ACS data for optimzation problem

# ratio of state weight sum and 'national' weight sum
df_wgt_factor <- 
  data %>% 
  group_by(stabbr) %>% 
  summarise(pwgtp_stateSum = sum(pwgtp)) %>% 
  mutate(wgt_factor = pwgtp_stateSum / sum(pwgtp_stateSum))


# To solve the optimization problem for 5 states, we need to create
# a data frame with 5 original df stacked together, each for an indiviudal state. 
state_names  <- as.character(data$stabbr) %>% unique %>% sort

data_stacked <- ldply(state_names, function(x) data %>% mutate(stabbr_original = stabbr, stabbr = x)) %>% 
  left_join(df_wgt_factor, by = "stabbr") %>% 
  rename(pwgtp_original = pwgtp) %>% 
  mutate(pwgtp = pwgtp_original * wgt_factor,
         weightp = pwgtp # to construct constraints on total weight
         )

# check the state totals
# data_stacked %>%
#   group_by(stabbr) %>% 
#   summarise(pwgtp_stateSum = sum(pwgtp))


# Constructing constraint coefficient df from recipe
cat("\nConstructing constraints...\n")
ccoef_sparse <- recipe %>% 
  rowwise() %>% 
  do(get_ccoefs2(., data_stacked)) %>% 
  ungroup
# count(ccoef_sparse, constraint_sort, constraint_name)

ccoef_lowN <- # constraints with low # of non-zero coefficients 
  count(ccoef_sparse, constraint_sort, constraint_name) %>% 
  filter(n <= nrow(data) / 1000)
# ccoef_lowN

ccoef_sparse %<>% 
  filter((!constraint_name %in% ccoef_lowN$constraint_name) | constraint_sort >= 436) %>% 
# ONLY AFTER all filtering is done do we assign constraint numbers, as some
  # may drop out if they have no nonzero coefficients %>%
  mutate(constraint_num = group_indices(., constraint_sort)) %>%
  arrange(constraint_num, row_num) %>% 
  select(constraint_num, everything())
# count(ccoef_sparse, constraint_num, constraint_sort, constraint_name)


ccoef_sparse_tgt <- recipe %>% 
  rowwise() %>% 
  do(get_ccoefs2(., data %>% mutate(pwgtp_original = pwgtp))) %>% 
  ungroup %>% 
  filter(constraint_sort %in% unique(ccoef_sparse$constraint_sort)) %>% 
  arrange(constraint_sort) %>%
  mutate(constraint_num = group_indices(., constraint_sort)) %>% 
  arrange(constraint_num, row_num) %>% 
  select(constraint_num, everything())
# ccoef_sparse_tgt %>% ht


input_tgt <- list(); input_tgt$ccoef_sparse <- ccoef_sparse_tgt
target_vals <- eval_g_sparse(rep(1, nrow(data)), input_tgt)
target_vals

# for comparison
input_init <- list(); input_init$ccoef_sparse <- ccoef_sparse
init_vals <- eval_g_sparse(rep(1, nrow(data_stacked)), input_init)

# comparing target state and file value
# ccoef_sparse %>% count(constraint_num, constraint_name) %>%
#   mutate(targets = targets_vals,
#          init_vals  = init_vals ,
#          ratio = targets / init_vals)






# Inputs for the function

x0 <- rep(1, nrow(data_stacked))

inputs_full <- list()
inputs_full$p <- 2
inputs_full$s      <- 0.01
inputs_full$weight <- data_stacked$pwgtp
inputs_full$ccoef_sparse <- ccoef_sparse
inputs_full$jac_vector <- jac_flatten_sparse(inputs_full$ccoef_sparse)

inputs_full$target_vals <- target_vals
inputs_full$wgt_factor   <- df_wgt_factor

# create vectors with constraint lower bounds and upper bounds - if they are the same, we have equality constraints
# create vectors with constraint lower bounds and upper bounds
# define tolerance - for simplicity, use the same for all, but that is not necessary

n_c1 <- length(target_vals) - nrow(data) 
n_c2 <- nrow(data) 

tol <- c(rep(.01, n_c1), rep(0, n_c2))  # 1% range for non-record-wise constraints

clb <- target_vals
clb <- clb - tol * abs(clb)

cub <- target_vals
cub <- cub + tol * abs(clb)
#cbind(init_vals, target_single_state, clb, cub)

# structure of Jaobian
eval_jac_g_structure_sparse <- define_jac_g_structure_sparse(inputs_full$ccoef_sparse)

# structure of Hessian
eval_h_structure <- hess_structure(length(inputs_full$weight))

# set arbitrary bounds for x that fall inside the solution above
xlb <- rep(0.3,  length(inputs_full$weight))
xub <- rep(30, length(inputs_full$weight))

opts <- list("print_level" = 0,
             "file_print_level" = 5, # integer
             "linear_solver" = "ma27", # mumps pardiso ma27 ma57 ma77 ma86 ma97
             "max_iter"=1000)

opts$output_file <- paste0(PROJHOME, "/task2/results/prob_5states.out")
opts$obj_scaling_factor <- 1 # default 1 
opts$nlp_scaling_max_gradient <- 100 # default 100 -- not changing this now
#opts  


# Choosing objective function

# obj_fn <- c("xtop", "absapprox")[2]

if(obj_fn == "xtop"){
  eval_f_select           = eval_f_xtop          # function, arguments: x, inputs
  eval_grad_f_select      = eval_grad_f_xtop     # function, arguments: x, inputs
  eval_h_select           = eval_h_xtop          # function, arguments: x, inputs, (obj_factor, hessian_lambda)
}

if(obj_fn == "absapprox"){
  eval_f_select           = eval_f_absapprox          # function, arguments: x, inputs
  eval_grad_f_select      = eval_grad_f_absapprox     # function, arguments: x, inputs
  eval_h_select           = eval_h_absapprox          # function, arguments: x, inputs, (obj_factor, hessian_lambda)
}


cat("\nSolving the optimization problem...\n")
result <- ipoptr(x0 = x0,
                 lb = xlb,
                 ub = xub,
                 
                 eval_f           = eval_f_select,          # function, arguments: x, inputs
                 eval_grad_f      = eval_grad_f_select,     # function, arguments: x, inputs
                 eval_h           = eval_h_select,          # function, arguments: x, inputs, (obj_factor, hessian_lambda)
                
                 
                 eval_h_structure = eval_h_structure,     # list, structure of Hessian
                 
                 eval_g = eval_g_sparse,                  # function, constraints LHS - a vector of values, arguments: x, inputs
                 eval_jac_g = eval_jac_g,                 # function, extract inputs$jac_vector, arguments: x, inputs
                 eval_jac_g_structure = eval_jac_g_structure_sparse, # list, structure of Jacobian
                 
                 constraint_lb = clb, 
                 constraint_ub = cub,
                 
                 opts   = opts,
                 inputs = inputs_full
                 )
 
 
 cat(result$message)
 cat("status:", result$status) 
 cat("iterations: ", result$iterations)
 cat("objective: ", result$objective)
 cat("Distribution of the solution:","\n")
 print(quantile(result$solution, probs = c(0, .05, .1, .25, .5, .75, .9, .95, 1)))
 
 # names(output$result) %>% sort

 calcsums <- eval_g_sparse(x=result$solution, inputs_full)
 comparison <- cbind(init_vals, target_vals, calcsums, calcsums/target_vals)
 rownames(comparison) <- ccoef_sparse %>% count(constraint_num, constraint_name) %>% pull(constraint_name)
  x <- comparison 
 
 output <- list()
 output$inputs <- inputs_full
 output$result <- result
 output$comparison <- comparison
 
 return(output)
 
}


# output <- run_ipopt("NY", recipe, "xtop")


system.time({output <- run_ipopt_allstates(recipe, "xtop")})
# Takes about 130s 
# Memory usage is  (2.5Gb used by R and RStudio), potential for much larger problems (more states)

# output$result$message; output$result$status; output$result$iterations
# output$result$objective
# quantile(output$result$solution, probs = c(0, .05, .1, .25, .5, .75, .9, .95, 1))
# result_single_state <- result
  
```


# Comparing the re-weighted data with the true single state data

1.  distributions of individual variables 
2.  covariance matrix


```{r compare percentiles}
# Examine distributions of individual variables 


compare_ptiles <- function(var_,
                           state_select,
                           data,
                           result,
                           pts = c(0, .05, .1, .25, .5, .75, .9, .95,.99, 1)
                           ){

# var_ <- "retp"
# data <-  acs_subset
# result <- output$result
# state_select <- "All"
# pts = c(0, .05, .1, .25, .5, .75, .9, .95,.99, 1)

if (state_select == "All"){
  target_state <- as.character(data$stabbr) %>% unique
  } else target_state <- state_select

state_names <- as.character(acs_subset$stabbr) %>% unique %>% sort
data_stacked <- ldply(state_names, function(x) data %>% mutate(stabbr_original = stabbr, stabbr = x)) %>% 
  left_join(mutate(output$inputs$wgt_factor, stabbr = as.character(stabbr)), by = "stabbr") %>% 
  mutate(pwgtp = pwgtp * wgt_factor, 
         x = result$solution,
         pwgtp_rewgt = pwgtp * x) %>% 
  filter(stabbr %in% target_state) 

data_select <- 
  data %>% filter(stabbr %in% target_state)

comparison <- 
  bind_rows(
    Hmisc::wtd.quantile(data_stacked[[var_]], data_stacked$pwgtp, pts),                                      # w/ original weight
    Hmisc::wtd.quantile(data_select[[var_]],  data_select$pwgtp, pts), # target
    Hmisc::wtd.quantile(data_stacked[[var_]], data_stacked$pwgtp_rewgt, pts)                       # reweighted
)

return(comparison)
}


# Targeted
compare_ptiles("pincp", "All", acs_subset, output$result)
compare_ptiles("wagp",  "All", acs_subset, output$result)
compare_ptiles("intp",  "All", acs_subset, output$result)
compare_ptiles("retp",  "All", acs_subset, output$result)
compare_ptiles("ssp",   "All", acs_subset, output$result)

# Not targeted
compare_ptiles("pap",   "All", acs_subset, output$result)
compare_ptiles("ssip",  "All", acs_subset, output$result)


# Targeted
compare_ptiles("pincp", "NY", acs_subset, output$result)
compare_ptiles("wagp",  "NY", acs_subset, output$result)
compare_ptiles("intp",  "NY", acs_subset, output$result)
compare_ptiles("retp",  "NY", acs_subset, output$result)
compare_ptiles("ssp",   "NY", acs_subset, output$result)

# Not targeted
compare_ptiles("pap",   "NY", acs_subset, output$result)
compare_ptiles("ssip",  "NY", acs_subset, output$result)


# Targeted
compare_ptiles("pincp", "CA", acs_subset, output$result)
compare_ptiles("wagp",  "CA", acs_subset, output$result)
compare_ptiles("intp",  "CA", acs_subset, output$result)
compare_ptiles("retp",  "CA", acs_subset, output$result)
compare_ptiles("ssp",   "CA", acs_subset, output$result)

# Not targeted
compare_ptiles("pap",   "CA", acs_subset, output$result)
compare_ptiles("ssip",  "CA", acs_subset, output$result)


# Targeted
compare_ptiles("pincp", "TX", acs_subset, output$result)
compare_ptiles("wagp",  "TX", acs_subset, output$result)
compare_ptiles("intp",  "TX", acs_subset, output$result)
compare_ptiles("retp",  "TX", acs_subset, output$result)
compare_ptiles("ssp",   "TX", acs_subset, output$result)

# Not targeted
compare_ptiles("pap",   "TX", acs_subset, output$result)
compare_ptiles("ssip",  "TX", acs_subset, output$result)


# Targeted
compare_ptiles("pincp", "IL", acs_subset, output$result)
compare_ptiles("wagp",  "IL", acs_subset, output$result)
compare_ptiles("intp",  "IL", acs_subset, output$result)
compare_ptiles("retp",  "IL", acs_subset, output$result)
compare_ptiles("ssp",   "IL", acs_subset, output$result)

# Not targeted
compare_ptiles("pap",   "IL", acs_subset, output$result)
compare_ptiles("ssip",  "IL", acs_subset, output$result)


# Targeted
compare_ptiles("pincp", "FL", acs_subset, output$result)
compare_ptiles("wagp",  "FL", acs_subset, output$result)
compare_ptiles("intp",  "FL", acs_subset, output$result)
compare_ptiles("retp",  "FL", acs_subset, output$result)
compare_ptiles("ssp",   "FL", acs_subset, output$result)

# Not targeted
compare_ptiles("pap",   "FL", acs_subset, output$result)
compare_ptiles("ssip",  "FL", acs_subset, output$result)
`





````


```{r compare_ecdf}

compare_ecdf <- function(var_,
                         state_select,
                         data,
                         result,
                         cutoff = 0.95){


# var_ <- "retp"
# data <-  acs_subset
# result <- output$result 
# state_select <- "All"
# cutoff <- 0.95

if (state_select == "All"){
  target_state <- as.character(data$stabbr) %>% unique
  } else target_state <- state_select

state_names <- as.character(acs_subset$stabbr) %>% unique %>% sort
data_stacked <- ldply(state_names, function(x) data %>% mutate(stabbr_original = stabbr, stabbr = x)) %>% 
  left_join(mutate(output$inputs$wgt_factor, stabbr = as.character(stabbr)), by = "stabbr") %>% 
  mutate(pwgtp = pwgtp * wgt_factor, 
         x = result$solution,
         pwgtp_rewgt = pwgtp * x) %>% 
  filter(stabbr %in% target_state) 


data_select <- 
  data %>% filter(stabbr %in% target_state)

 ecdf_org <- Hmisc::wtd.Ecdf(data_stacked[[var_]], data_stacked$pwgtp)                                      # w/ original weight
 ecdf_tgt <- Hmisc::wtd.Ecdf(data_select[[var_]],  data_select$pwgtp) # target
 ecdf_rwt <- Hmisc::wtd.Ecdf(data_stacked[[var_]], data_stacked$pwgtp_rewgt)
                             
bind_rows(
 as_tibble(ecdf_org) %>% mutate(type = "org"),
 as_tibble(ecdf_tgt) %>% mutate(type = paste0("tgt_", state_select)),
 as_tibble(ecdf_rwt) %>% mutate(type = paste0("rwt_", state_select))
) %>% 
  mutate(type = factor(type, levels = c("org", paste0("tgt_", state_select), paste0("rwt_", state_select)))) %>% 
  filter(ecdf <= cutoff) %>% 
  ggplot(aes(x = x, y = ecdf, color = type)) + theme_bw() + 
  geom_line() +
  coord_cartesian(ylim = c(0,1))+
  scale_color_manual(values = c("grey40", "red", "blue"))+
  labs(x = NULL,
       title = paste0("Comparing ECDF \nTarget state: ", state_select, "\nVariable: ", var_))
 
}


compare_ecdf("pincp", "All", acs_subset, output$result)
compare_ecdf("wagp",  "All", acs_subset, output$result)
compare_ecdf("intp",  "All", acs_subset, output$result)
compare_ecdf("retp",  "All", acs_subset, output$result)
compare_ecdf("ssp",   "All", acs_subset, output$result)

compare_ecdf("pincp", "NY", acs_subset, output$result)
compare_ecdf("wagp",  "NY", acs_subset, output$result)
compare_ecdf("intp",  "NY", acs_subset, output$result)
compare_ecdf("retp",  "NY", acs_subset, output$result)
compare_ecdf("ssp",   "NY", acs_subset, output$result)

compare_ecdf("pincp", "CA", acs_subset, output$result)
compare_ecdf("wagp",  "CA", acs_subset, output$result)
compare_ecdf("intp",  "CA", acs_subset, output$result)
compare_ecdf("retp",  "CA", acs_subset, output$result)
compare_ecdf("ssp",   "CA", acs_subset, output$result)

compare_ecdf("pincp", "TX", acs_subset, output$result)
compare_ecdf("wagp",  "TX", acs_subset, output$result)
compare_ecdf("intp",  "TX", acs_subset, output$result)
compare_ecdf("retp",  "TX", acs_subset, output$result)
compare_ecdf("ssp",   "TX", acs_subset, output$result)

compare_ecdf("pincp", "IL", acs_subset, output$result)
compare_ecdf("wagp",  "IL", acs_subset, output$result)
compare_ecdf("intp",  "IL", acs_subset, output$result)
compare_ecdf("retp",  "IL", acs_subset, output$result)
compare_ecdf("ssp",   "IL", acs_subset, output$result)

compare_ecdf("pincp", "FL", acs_subset, output$result)
compare_ecdf("wagp",  "FL", acs_subset, output$result)
compare_ecdf("intp",  "FL", acs_subset, output$result)
compare_ecdf("retp",  "FL", acs_subset, output$result)
compare_ecdf("ssp",   "FL", acs_subset, output$result)


# Note
#  - negative interest income in IL


```


```{r correlation}

compare_corr <- function(var_,
                         state_select,
                         data,
                         result){

var_ <- "pincp"
data <-  acs_subset
result <- output$result
state_select <- "All"

if (state_select == "All"){
  target_state <- as.character(data$stabbr) %>% unique
  } else target_state <- state_select

state_names <- as.character(acs_subset$stabbr) %>% unique %>% sort
data_stacked <- ldply(state_names, function(x) data %>% mutate(stabbr_original = stabbr, stabbr = x)) %>% 
  left_join(mutate(output$inputs$wgt_factor, stabbr = as.character(stabbr)), by = "stabbr") %>% 
  mutate(pwgtp = pwgtp * wgt_factor, 
         x = result$solution,
         pwgtp_rewgt = pwgtp * x) %>% 
  filter(stabbr %in% target_state) 

data_select <- 
  data %>% filter(stabbr %in% target_state)

cor_org <- weights::wtd.cors(select(data_stacked, pincp, wagp, intp, retp, ssp) %>% as.matrix, weight = data_stacked$pwgtp)
cor_tgt <- weights::wtd.cors(select(data_select,  pincp, wagp, intp, retp, ssp) %>% as.matrix, weight = data_select$pwgtp)
cor_rwt <- weights::wtd.cors(select(data_stacked, pincp, wagp, intp, retp, ssp) %>% as.matrix, weight = data_stacked$pwgtp_rewgt)

list(org = cor_org,
     tgt = cor_tgt,
     rwt = cor_rwt)
}

compare_corr("pincp", "All", acs_subset, output$result)

compare_corr("pincp", "NY", acs_subset, output$result)
compare_corr("pincp", "CA", acs_subset, output$result)
compare_corr("pincp", "TX", acs_subset, output$result)
compare_corr("pincp", "IL", acs_subset, output$result)
compare_corr("pincp", "FL", acs_subset, output$result)

# Improvement for correlation between pincp and other vars. 
# Correlation between other vars are quite low. 



data_stacked <- ldply(state_names, function(x) data %>% mutate(stabbr_original = stabbr, stabbr = x)) %>% 
  left_join(mutate(output$inputs$wgt_factor, stabbr = as.character(stabbr)), by = "stabbr") %>% 
  mutate(pwgtp = pwgtp * wgt_factor, 
         x = result$solution,
         pwgtp_rewgt = pwgtp * x) %>% 
  filter(stabbr %in% target_state) 

df <- data_stacked %>% filter(serialno == 2015000271836)

df$pwgtp %>% sum
df$pwgtp_rewgt %>% sum


df <- data_stacked %>% select(serialno, sporder, stabbr, pwgtp_rewgt, weightp) %>%
  spread(stabbr, pwgtp_rewgt) %>% 
  mutate(tot = CA + FL+ IL + NY + TX,
         diff = (weightp - tot)/weightp )
  
df$diff %>% quantile(c(0, 0.01, 0.05, 0.25, .5, .75, .90, .99, 1))





```
















